parameters:
    locale: nl_NL

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $logger: '@surfnet_gssp.logger'
            $stateHandler: '@surfnet_gssp.state_handler.service'
            $supportUrl: '%support_url%'
            $supportEmail: '%support_email%'
            $locales: '%locales%'
            $userDisplayName: '%user_display_name%'
            $trustedCertificatesDirectory: '%trusted_certificates_directory%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    App\Repository\:
        resource: '../src/Repository/*'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Surfnet\GsspBundle\Service\ValueStore\SessionValueStore:
        alias: surfnet_gssp.value_store.service

    App\Service\InMemoryAttestationCertificateTrustStore:
        arguments:
            - '$trustedCertificates': []

    App\Service\AttestationCertificateTrustStore:
        factory: '@App\Service\AttestationCertificateTrustStoreFactory'
